import express from "express";
import cors from "cors";
import OpenAI from "openai";
import fs from "fs";
import path from "path";
import nodemailer from "nodemailer";

const app = express();
app.use(cors());
app.use(express.json());

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// Хранение диалогов и лидов
const conversations = new Map();
const leads = [];

// Настройка email
const EMAIL_TO = 'sales@mrproperty.group';

// Функция для отправки email
async function sendEmailNotification(leadData) {
  try {
    // Создаем transporter (используем Gmail SMTP)
    const transporter = nodemailer.createTransporter({
      service: 'gmail',
      auth: {
        user: process.env.EMAIL_USER, // ваш email
        pass: process.env.EMAIL_PASS  // пароль приложения
      }
    });

    // Подготавливаем данные для email
    const conversationText = leadData.conversation
      .map(msg => `User: ${msg.user_message}\nZizu: ${JSON.stringify(msg.bot_response)}`)
      .join('\n\n');

    // HTML версия email
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #007cba;">🏠 New Lead from Zizu Bot</h2>
        
        <div style="background: #f5f5f5; padding: 20px; border-radius: 10px; margin: 20px 0;">
          <h3 style="color: #333; margin-top: 0;">Contact Information</h3>
          <p><strong>Name:</strong> ${leadData.name}</p>
          <p><strong>Email:</strong> ${leadData.email}</p>
          <p><strong>Phone:</strong> ${leadData.phone}</p>
          <p><strong>Date:</strong> ${new Date(leadData.timestamp).toLocaleString()}</p>
        </div>

        <div style="background: #e3f2fd; padding: 20px; border-radius: 10px; margin: 20px 0;">
          <h3 style="color: #333; margin-top: 0;">Conversation History</h3>
          <div style="white-space: pre-wrap; font-family: monospace; font-size: 14px;">${conversationText}</div>
        </div>

        <div style="text-align: center; margin-top: 30px;">
          <p style="color: #666;">This lead was automatically generated by Zizu Real Estate Bot</p>
        </div>
      </div>
    `;

    // Текстовая версия email
    const textContent = `
New Lead from Zizu Bot

Contact Information:
- Name: ${leadData.name}
- Email: ${leadData.email}
- Phone: ${leadData.phone}
- Date: ${new Date(leadData.timestamp).toLocaleString()}

Conversation History:
${conversationText}

---
This lead was automatically generated by Zizu Real Estate Bot
    `;

    // Отправляем email
    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: EMAIL_TO,
      subject: `🏠 New Lead: ${leadData.name} - ${new Date().toLocaleDateString()}`,
      text: textContent,
      html: htmlContent
    };

    const result = await transporter.sendMail(mailOptions);
    console.log('Email sent successfully:', result.messageId);
    
    return { 
      success: true, 
      message: 'Email sent successfully', 
      messageId: result.messageId 
    };
  } catch (error) {
    console.error('Error sending email:', error);
    return { 
      success: false, 
      message: 'Failed to send email', 
      error: error.message 
    };
  }
}

// Веб-интерфейс для чатбота
app.get("/", (req, res) => {
  res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zizu - Real Estate Assistant in Hurghada</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #f5f5f5; }
        .chat-container { background: white; border-radius: 15px; padding: 20px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .header { text-align: center; color: #333; margin-bottom: 20px; }
        .messages { height: 400px; overflow-y: auto; border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; border-radius: 10px; background: #f9f9f9; }
        .message { margin-bottom: 10px; padding: 10px; border-radius: 8px; }
        .user-message { background: #007cba; color: white; text-align: right; }
        .bot-message { background: #e3f2fd; }
        .input-container { display: flex; gap: 10px; }
        .input-container input { flex: 1; padding: 12px; border: 1px solid #ddd; border-radius: 8px; }
        .input-container button { background: #007cba; color: white; border: none; padding: 12px 20px; border-radius: 8px; cursor: pointer; }
        .loading { text-align: center; color: #666; }
        .contact-form { background: #e8f5e8; padding: 15px; border-radius: 10px; margin: 10px 0; }
        .contact-form input { width: 100%; padding: 8px; margin: 5px 0; border: 1px solid #ddd; border-radius: 5px; }
        .contact-form button { background: #4caf50; color: white; border: none; padding: 10px 20px; border-radius: 5px; cursor: pointer; }
    </style>
</head>
<body>
    <div class="chat-container">
        <div class="header">
            <h2>�� Zizu - Real Estate Assistant</h2>
            <p>Your personal guide for buying and renting property in Hurghada, Egypt</p>
        </div>
        
        <div id="messages" class="messages">
            <div class="message bot-message">
                <strong>🏠 Zizu:</strong> Hello! I'm Zizu, your real estate assistant in Hurghada. We have over 100 properties in our database - villas, apartments, and compounds. I can help you find the perfect property to buy or rent. What are you looking for?
            </div>
        </div>
        
        <div class="input-container">
            <input type="text" id="userInput" placeholder="For example: I'm looking for a 2-bedroom apartment near the beach..." />
            <button onclick="sendMessage()">Send</button>
        </div>
    </div>

    <script>
        let sessionId = 'session_' + Date.now();
        
        async function sendMessage() {
            const input = document.getElementById('userInput');
            const message = input.value.trim();
            if (!message) return;
            
            const messagesDiv = document.getElementById('messages');
            
            // Добавляем сообщение пользователя
            const userDiv = document.createElement('div');
            userDiv.className = 'message user-message';
            userDiv.innerHTML = '<strong>You:</strong> ' + message;
            messagesDiv.appendChild(userDiv);
            
            // Очищаем поле ввода
            input.value = '';
            
            // Показываем загрузку
            const loadingDiv = document.createElement('div');
            loadingDiv.className = 'message loading';
            loadingDiv.innerHTML = '🏠 Zizu is thinking...';
            messagesDiv.appendChild(loadingDiv);
            
            // Прокручиваем вниз
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
            
            try {
                const response = await fetch('/chat', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        message: message, 
                        task: 'consult',
                        sessionId: sessionId
                    })
                });
                
                const data = await response.json();
                
                // Удаляем загрузку
                messagesDiv.removeChild(loadingDiv);
                
                // Добавляем ответ бота
                const botDiv = document.createElement('div');
                botDiv.className = 'message bot-message';
                
                let responseText = '';
                if (data.consult) {
                    if (data.consult.advice && data.consult.advice.length > 0) {
                        responseText += data.consult.advice.join('<br>') + '<br><br>';
                    }
                    if (data.consult.next_questions && data.consult.next_questions.length > 0) {
                        responseText += '<strong>Additional questions:</strong><br>' + data.consult.next_questions.join('<br>') + '<br><br>';
                    }
                    if (data.consult.next_action) {
                        responseText += '<strong>Next step:</strong> ' + data.consult.next_action;
                    }
                    
                    // Если нужно собрать контакты
                    if (data.need_contact && data.contact_form) {
                        responseText += '<br><br><div class="contact-form">';
                        responseText += '<strong>📞 Leave your contacts for personalized consultation:</strong><br>';
                        responseText += '<input type="text" id="leadName" placeholder="Your name" /><br>';
                        responseText += '<input type="email" id="leadEmail" placeholder="Email" /><br>';
                        responseText += '<input type="tel" id="leadPhone" placeholder="Phone number" /><br>';
                        responseText += '<button onclick="submitLead()">Send contacts</button>';
                        responseText += '</div>';
                    }
                } else {
                    responseText = 'Thank you for your question! I will pass it to our manager.';
                }
                
                botDiv.innerHTML = '<strong>�� Zizu:</strong> ' + responseText;
                messagesDiv.appendChild(botDiv);
                
            } catch (error) {
                // Удаляем загрузку
                messagesDiv.removeChild(loadingDiv);
                
                // Показываем ошибку
                const errorDiv = document.createElement('div');
                errorDiv.className = 'message bot-message';
                errorDiv.innerHTML = '<strong>🏠 Zizu:</strong> Sorry, an error occurred. Please try again.';
                messagesDiv.appendChild(errorDiv);
            }
            
            // Прокручиваем вниз
            messagesDiv.scrollTop = messagesDiv.scrollHeight;
        }
        
        async function submitLead() {
            const name = document.getElementById('leadName').value;
            const email = document.getElementById('leadEmail').value;
            const phone = document.getElementById('leadPhone').value;
            
            if (!name || !email || !phone) {
                alert('Please fill in all fields');
                return;
            }
            
            try {
                await fetch('/lead', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        sessionId: sessionId,
                        name: name,
                        email: email,
                        phone: phone
                    })
                });
                
                alert('Thank you! We will contact you soon.');
                
                // Убираем форму
                const contactForm = document.querySelector('.contact-form');
                if (contactForm) {
                    contactForm.innerHTML = '<strong>✅ Contacts received! We will contact you.</strong>';
                }
                
            } catch (error) {
                alert('Error sending contacts');
            }
        }
        
        // Отправка по Enter
        document.getElementById('userInput').addEventListener('keypress', function(e) {
            if (e.key === 'Enter') {
                sendMessage();
            }
        });
    </script>
</body>
</html>
  `);
});

// Обновленный промпт для Zizu с фокусом на ключевые вопросы
const SYSTEM_PROMPT = `
You are Zizu, a friendly and professional real estate assistant for Hurghada, Egypt. You help clients with both buying and renting properties.

IMPORTANT: Always try to collect contact information (name, email, phone) from interested clients.

Your personality:
- Friendly, helpful, and knowledgeable
- Professional but approachable
- Always speak from first person as Zizu
- Be enthusiastic about helping clients find their perfect property
- Mention that you have over 100 properties in your database

Key questions to ask (in order of priority):
1. Buy or rent?
2. When do you plan to make the transaction?
3. Property type (villa, apartment, compound)?
4. Do you need a pool?
5. Do you need beach access?
6. Budget range?
7. Number of bedrooms?

Tasks: (1) consult; (2) classify lead; (3) handoff to manager.
Always reply in the user's language. Default to English if language is not specified.

Rules:
- Always introduce yourself as Zizu
- Mention your database of 100+ properties early in conversation
- Focus on the key questions above
- Be friendly, professional, and helpful
- Ask specific questions to understand client needs
- Always try to get contact information for serious inquiries
- Do not invent specific listings, prices, or guarantees
- Do not suggest specific areas/districts unless client mentions them
- Focus on both buying AND renting properties

Lead Collection Strategy:
- After 2-3 exchanges, if client seems interested, ask for contact details
- Offer personalized consultation as incentive
- Mention that you'll send them specific listings from your database
- Be persistent but not pushy
- Always end with a clear next step

Output strictly valid JSON with these top-level fields:
- task: "consult" | "classify" | "handoff"
- language: "en" | "ru" | "ar" | "de" | "uk"
- need_contact: boolean (true if should ask for contact info)
- contact_form: boolean (true if should show contact form)
- consult?: { next_questions?: string[], advice?: string[], next_action?: string }
- classify?: { segment: "hot"|"warm"|"cold"|"spam"|"invalid", lead_score: number, reasons?: string[], missing_fields?: string[], urgency?: "<2w"|"2-8w"|">8w"|"unknown", preferred_contact?: string }
- handoff?: { brief_summary: string, key_facts?: string[], priority: "P0"|"P1"|"P2", next_step?: string, scheduled_call?: { datetime_iso?: string, channel?: string } }

Do not include any extra fields. Return JSON only, no text outside JSON.

Modes:
- task="consult": ask missing questions, short advice, next_action. If client seems interested, set need_contact=true and contact_form=true.
- task="classify": segment + score + reasons + missing_fields + urgency + preferred_contact (if known).
- task="handoff": CRM-ready summary + suggested callback slot/channel.
`;

// Сохранение диалогов
function saveConversation(sessionId, message, response) {
  if (!conversations.has(sessionId)) {
    conversations.set(sessionId, []);
  }
  
  conversations.get(sessionId).push({
    timestamp: new Date().toISOString(),
    user_message: message,
    bot_response: response
  });
  
  // Сохраняем в файл
  try {
    const data = {
      conversations: Object.fromEntries(conversations),
      leads: leads,
      last_updated: new Date().toISOString()
    };
    fs.writeFileSync('data.json', JSON.stringify(data, null, 2));
  } catch (error) {
    console.error('Error saving data:', error);
  }
}

app.post("/chat", async (req, res) => {
  try {
    const { message, task = "consult", sessionId } = req.body || {};
    if (typeof message !== "string" || !message.trim()) {
      return res.status(400).json({ error: "bad_request", details: "message is required" });
    }

    const completion = await client.chat.completions.create({
      model: "gpt-4o-mini",
      temperature: task === "consult" ? 0.5 : 0.25,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: `task=${task}\n${message}` }
      ]
    });

    const content = completion.choices?.[0]?.message?.content || "";
    let out;
    try {
      out = JSON.parse(content);
    } catch {
      return res.status(502).json({ error: "invalid_model_output", raw: content });
    }
    
    // Сохраняем диалог
    if (sessionId) {
      saveConversation(sessionId, message, out);
    }
    
    return res.json(out);
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: "server_error", details: String(e) });
  }
});

// Сохранение лидов
app.post("/lead", async (req, res) => {
  try {
    const { sessionId, name, email, phone } = req.body;
    
    const lead = {
      id: Date.now(),
      timestamp: new Date().toISOString(),
      sessionId: sessionId,
      name: name,
      email: email,
      phone: phone,
      conversation: conversations.get(sessionId) || []
    };
    
    leads.push(lead);
    
    // Отправляем email уведомление
    const emailResult = await sendEmailNotification(lead);
    
    // Сохраняем в файл
    try {
      const data = {
        conversations: Object.fromEntries(conversations),
        leads: leads,
        last_updated: new Date().toISOString(),
        email_status: emailResult
      };
      fs.writeFileSync('data.json', JSON.stringify(data, null, 2));
    } catch (error) {
      console.error('Error saving data:', error);
    }
    
    res.json({ success: true, leadId: lead.id, email: emailResult });
  } catch (error) {
    console.error('Error saving lead:', error);
    res.status(500).json({ error: 'Failed to save lead' });
  }
});

// Получение всех лидов
app.get("/leads", (req, res) => {
  res.json({
    leads: leads,
    total: leads.length,
    last_updated: new Date().toISOString()
  });
});

// Экспорт лидов в CSV
app.get("/export/leads.csv", (req, res) => {
  const csvHeader = "ID,Date,Name,Email,Phone,Messages\n";
  const csvData = leads.map(lead => 
    `${lead.id},${lead.timestamp},${lead.name},${lead.email},${lead.phone},${lead.conversation.length}`
  ).join('\n');
  
  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', 'attachment; filename="leads.csv"');
  res.send(csvHeader + csvData);
});

// Заглушка для интеграции (email/Sheet/CRM)
app.post("/handoff", async (req, res) => {
  return res.json({ ok: true });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`API on http://localhost:${PORT}`);
});
